// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class MoveData;
struct MoveDataDefaultTypeInternal;
extern MoveDataDefaultTypeInternal _MoveData_default_instance_;
class PlayerData;
struct PlayerDataDefaultTypeInternal;
extern PlayerDataDefaultTypeInternal _PlayerData_default_instance_;
class Vec3;
struct Vec3DefaultTypeInternal;
extern Vec3DefaultTypeInternal _Vec3_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::MoveData* Arena::CreateMaybeMessage<::Protocol::MoveData>(Arena*);
template<> ::Protocol::PlayerData* Arena::CreateMaybeMessage<::Protocol::PlayerData>(Arena*);
template<> ::Protocol::Vec3* Arena::CreateMaybeMessage<::Protocol::Vec3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class PlayerData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PlayerData) */ {
 public:
  inline PlayerData() : PlayerData(nullptr) {}
  ~PlayerData() override;
  explicit PROTOBUF_CONSTEXPR PlayerData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerData(const PlayerData& from);
  PlayerData(PlayerData&& from) noexcept
    : PlayerData() {
    *this = ::std::move(from);
  }

  inline PlayerData& operator=(const PlayerData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerData& operator=(PlayerData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerData* internal_default_instance() {
    return reinterpret_cast<const PlayerData*>(
               &_PlayerData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerData& a, PlayerData& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerData& from) {
    PlayerData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PlayerData";
  }
  protected:
  explicit PlayerData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserNameFieldNumber = 2,
    kMoveDataFieldNumber = 3,
    kUidFieldNumber = 1,
  };
  // string userName = 2;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // .Protocol.MoveData moveData = 3;
  bool has_movedata() const;
  private:
  bool _internal_has_movedata() const;
  public:
  void clear_movedata();
  const ::Protocol::MoveData& movedata() const;
  PROTOBUF_NODISCARD ::Protocol::MoveData* release_movedata();
  ::Protocol::MoveData* mutable_movedata();
  void set_allocated_movedata(::Protocol::MoveData* movedata);
  private:
  const ::Protocol::MoveData& _internal_movedata() const;
  ::Protocol::MoveData* _internal_mutable_movedata();
  public:
  void unsafe_arena_set_allocated_movedata(
      ::Protocol::MoveData* movedata);
  ::Protocol::MoveData* unsafe_arena_release_movedata();

  // uint64 uid = 1;
  void clear_uid();
  uint64_t uid() const;
  void set_uid(uint64_t value);
  private:
  uint64_t _internal_uid() const;
  void _internal_set_uid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PlayerData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::Protocol::MoveData* movedata_;
    uint64_t uid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class MoveData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.MoveData) */ {
 public:
  inline MoveData() : MoveData(nullptr) {}
  ~MoveData() override;
  explicit PROTOBUF_CONSTEXPR MoveData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MoveData(const MoveData& from);
  MoveData(MoveData&& from) noexcept
    : MoveData() {
    *this = ::std::move(from);
  }

  inline MoveData& operator=(const MoveData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MoveData& operator=(MoveData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MoveData& default_instance() {
    return *internal_default_instance();
  }
  static inline const MoveData* internal_default_instance() {
    return reinterpret_cast<const MoveData*>(
               &_MoveData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MoveData& a, MoveData& b) {
    a.Swap(&b);
  }
  inline void Swap(MoveData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MoveData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MoveData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MoveData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MoveData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MoveData& from) {
    MoveData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MoveData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.MoveData";
  }
  protected:
  explicit MoveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 3,
    kRotationFieldNumber = 4,
    kMoveDirFieldNumber = 5,
  };
  // .Protocol.Vec3 position = 3;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protocol::Vec3& position() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_position();
  ::Protocol::Vec3* mutable_position();
  void set_allocated_position(::Protocol::Vec3* position);
  private:
  const ::Protocol::Vec3& _internal_position() const;
  ::Protocol::Vec3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protocol::Vec3* position);
  ::Protocol::Vec3* unsafe_arena_release_position();

  // .Protocol.Vec3 rotation = 4;
  bool has_rotation() const;
  private:
  bool _internal_has_rotation() const;
  public:
  void clear_rotation();
  const ::Protocol::Vec3& rotation() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_rotation();
  ::Protocol::Vec3* mutable_rotation();
  void set_allocated_rotation(::Protocol::Vec3* rotation);
  private:
  const ::Protocol::Vec3& _internal_rotation() const;
  ::Protocol::Vec3* _internal_mutable_rotation();
  public:
  void unsafe_arena_set_allocated_rotation(
      ::Protocol::Vec3* rotation);
  ::Protocol::Vec3* unsafe_arena_release_rotation();

  // .Protocol.Vec3 moveDir = 5;
  bool has_movedir() const;
  private:
  bool _internal_has_movedir() const;
  public:
  void clear_movedir();
  const ::Protocol::Vec3& movedir() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_movedir();
  ::Protocol::Vec3* mutable_movedir();
  void set_allocated_movedir(::Protocol::Vec3* movedir);
  private:
  const ::Protocol::Vec3& _internal_movedir() const;
  ::Protocol::Vec3* _internal_mutable_movedir();
  public:
  void unsafe_arena_set_allocated_movedir(
      ::Protocol::Vec3* movedir);
  ::Protocol::Vec3* unsafe_arena_release_movedir();

  // @@protoc_insertion_point(class_scope:Protocol.MoveData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vec3* position_;
    ::Protocol::Vec3* rotation_;
    ::Protocol::Vec3* movedir_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Vec3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Vec3) */ {
 public:
  inline Vec3() : Vec3(nullptr) {}
  ~Vec3() override;
  explicit PROTOBUF_CONSTEXPR Vec3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec3(const Vec3& from);
  Vec3(Vec3&& from) noexcept
    : Vec3() {
    *this = ::std::move(from);
  }

  inline Vec3& operator=(const Vec3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3& operator=(Vec3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3* internal_default_instance() {
    return reinterpret_cast<const Vec3*>(
               &_Vec3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Vec3& a, Vec3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vec3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vec3& from) {
    Vec3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Vec3";
  }
  protected:
  explicit Vec3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Vec3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerData

// uint64 uid = 1;
inline void PlayerData::clear_uid() {
  _impl_.uid_ = uint64_t{0u};
}
inline uint64_t PlayerData::_internal_uid() const {
  return _impl_.uid_;
}
inline uint64_t PlayerData::uid() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerData.uid)
  return _internal_uid();
}
inline void PlayerData::_internal_set_uid(uint64_t value) {
  
  _impl_.uid_ = value;
}
inline void PlayerData::set_uid(uint64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerData.uid)
}

// string userName = 2;
inline void PlayerData::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& PlayerData::username() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerData.userName)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerData::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.PlayerData.userName)
}
inline std::string* PlayerData::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerData.userName)
  return _s;
}
inline const std::string& PlayerData::_internal_username() const {
  return _impl_.username_.Get();
}
inline void PlayerData::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerData::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerData::release_username() {
  // @@protoc_insertion_point(field_release:Protocol.PlayerData.userName)
  return _impl_.username_.Release();
}
inline void PlayerData::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.PlayerData.userName)
}

// .Protocol.MoveData moveData = 3;
inline bool PlayerData::_internal_has_movedata() const {
  return this != internal_default_instance() && _impl_.movedata_ != nullptr;
}
inline bool PlayerData::has_movedata() const {
  return _internal_has_movedata();
}
inline void PlayerData::clear_movedata() {
  if (GetArenaForAllocation() == nullptr && _impl_.movedata_ != nullptr) {
    delete _impl_.movedata_;
  }
  _impl_.movedata_ = nullptr;
}
inline const ::Protocol::MoveData& PlayerData::_internal_movedata() const {
  const ::Protocol::MoveData* p = _impl_.movedata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::MoveData&>(
      ::Protocol::_MoveData_default_instance_);
}
inline const ::Protocol::MoveData& PlayerData::movedata() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerData.moveData)
  return _internal_movedata();
}
inline void PlayerData::unsafe_arena_set_allocated_movedata(
    ::Protocol::MoveData* movedata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movedata_);
  }
  _impl_.movedata_ = movedata;
  if (movedata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.PlayerData.moveData)
}
inline ::Protocol::MoveData* PlayerData::release_movedata() {
  
  ::Protocol::MoveData* temp = _impl_.movedata_;
  _impl_.movedata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::MoveData* PlayerData::unsafe_arena_release_movedata() {
  // @@protoc_insertion_point(field_release:Protocol.PlayerData.moveData)
  
  ::Protocol::MoveData* temp = _impl_.movedata_;
  _impl_.movedata_ = nullptr;
  return temp;
}
inline ::Protocol::MoveData* PlayerData::_internal_mutable_movedata() {
  
  if (_impl_.movedata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::MoveData>(GetArenaForAllocation());
    _impl_.movedata_ = p;
  }
  return _impl_.movedata_;
}
inline ::Protocol::MoveData* PlayerData::mutable_movedata() {
  ::Protocol::MoveData* _msg = _internal_mutable_movedata();
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerData.moveData)
  return _msg;
}
inline void PlayerData::set_allocated_movedata(::Protocol::MoveData* movedata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.movedata_;
  }
  if (movedata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(movedata);
    if (message_arena != submessage_arena) {
      movedata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, movedata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.movedata_ = movedata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.PlayerData.moveData)
}

// -------------------------------------------------------------------

// MoveData

// .Protocol.Vec3 position = 3;
inline bool MoveData::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool MoveData::has_position() const {
  return _internal_has_position();
}
inline void MoveData::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
inline const ::Protocol::Vec3& MoveData::_internal_position() const {
  const ::Protocol::Vec3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(
      ::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& MoveData::position() const {
  // @@protoc_insertion_point(field_get:Protocol.MoveData.position)
  return _internal_position();
}
inline void MoveData::unsafe_arena_set_allocated_position(
    ::Protocol::Vec3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.MoveData.position)
}
inline ::Protocol::Vec3* MoveData::release_position() {
  
  ::Protocol::Vec3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vec3* MoveData::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protocol.MoveData.position)
  
  ::Protocol::Vec3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* MoveData::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::Protocol::Vec3* MoveData::mutable_position() {
  ::Protocol::Vec3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Protocol.MoveData.position)
  return _msg;
}
inline void MoveData::set_allocated_position(::Protocol::Vec3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protocol.MoveData.position)
}

// .Protocol.Vec3 rotation = 4;
inline bool MoveData::_internal_has_rotation() const {
  return this != internal_default_instance() && _impl_.rotation_ != nullptr;
}
inline bool MoveData::has_rotation() const {
  return _internal_has_rotation();
}
inline void MoveData::clear_rotation() {
  if (GetArenaForAllocation() == nullptr && _impl_.rotation_ != nullptr) {
    delete _impl_.rotation_;
  }
  _impl_.rotation_ = nullptr;
}
inline const ::Protocol::Vec3& MoveData::_internal_rotation() const {
  const ::Protocol::Vec3* p = _impl_.rotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(
      ::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& MoveData::rotation() const {
  // @@protoc_insertion_point(field_get:Protocol.MoveData.rotation)
  return _internal_rotation();
}
inline void MoveData::unsafe_arena_set_allocated_rotation(
    ::Protocol::Vec3* rotation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rotation_);
  }
  _impl_.rotation_ = rotation;
  if (rotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.MoveData.rotation)
}
inline ::Protocol::Vec3* MoveData::release_rotation() {
  
  ::Protocol::Vec3* temp = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vec3* MoveData::unsafe_arena_release_rotation() {
  // @@protoc_insertion_point(field_release:Protocol.MoveData.rotation)
  
  ::Protocol::Vec3* temp = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* MoveData::_internal_mutable_rotation() {
  
  if (_impl_.rotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3>(GetArenaForAllocation());
    _impl_.rotation_ = p;
  }
  return _impl_.rotation_;
}
inline ::Protocol::Vec3* MoveData::mutable_rotation() {
  ::Protocol::Vec3* _msg = _internal_mutable_rotation();
  // @@protoc_insertion_point(field_mutable:Protocol.MoveData.rotation)
  return _msg;
}
inline void MoveData::set_allocated_rotation(::Protocol::Vec3* rotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rotation_;
  }
  if (rotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rotation);
    if (message_arena != submessage_arena) {
      rotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:Protocol.MoveData.rotation)
}

// .Protocol.Vec3 moveDir = 5;
inline bool MoveData::_internal_has_movedir() const {
  return this != internal_default_instance() && _impl_.movedir_ != nullptr;
}
inline bool MoveData::has_movedir() const {
  return _internal_has_movedir();
}
inline void MoveData::clear_movedir() {
  if (GetArenaForAllocation() == nullptr && _impl_.movedir_ != nullptr) {
    delete _impl_.movedir_;
  }
  _impl_.movedir_ = nullptr;
}
inline const ::Protocol::Vec3& MoveData::_internal_movedir() const {
  const ::Protocol::Vec3* p = _impl_.movedir_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(
      ::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& MoveData::movedir() const {
  // @@protoc_insertion_point(field_get:Protocol.MoveData.moveDir)
  return _internal_movedir();
}
inline void MoveData::unsafe_arena_set_allocated_movedir(
    ::Protocol::Vec3* movedir) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movedir_);
  }
  _impl_.movedir_ = movedir;
  if (movedir) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.MoveData.moveDir)
}
inline ::Protocol::Vec3* MoveData::release_movedir() {
  
  ::Protocol::Vec3* temp = _impl_.movedir_;
  _impl_.movedir_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vec3* MoveData::unsafe_arena_release_movedir() {
  // @@protoc_insertion_point(field_release:Protocol.MoveData.moveDir)
  
  ::Protocol::Vec3* temp = _impl_.movedir_;
  _impl_.movedir_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* MoveData::_internal_mutable_movedir() {
  
  if (_impl_.movedir_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3>(GetArenaForAllocation());
    _impl_.movedir_ = p;
  }
  return _impl_.movedir_;
}
inline ::Protocol::Vec3* MoveData::mutable_movedir() {
  ::Protocol::Vec3* _msg = _internal_mutable_movedir();
  // @@protoc_insertion_point(field_mutable:Protocol.MoveData.moveDir)
  return _msg;
}
inline void MoveData::set_allocated_movedir(::Protocol::Vec3* movedir) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.movedir_;
  }
  if (movedir) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(movedir);
    if (message_arena != submessage_arena) {
      movedir = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, movedir, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.movedir_ = movedir;
  // @@protoc_insertion_point(field_set_allocated:Protocol.MoveData.moveDir)
}

// -------------------------------------------------------------------

// Vec3

// float x = 1;
inline void Vec3::clear_x() {
  _impl_.x_ = 0;
}
inline float Vec3::_internal_x() const {
  return _impl_.x_;
}
inline float Vec3::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.x)
  return _internal_x();
}
inline void Vec3::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Vec3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.x)
}

// float y = 2;
inline void Vec3::clear_y() {
  _impl_.y_ = 0;
}
inline float Vec3::_internal_y() const {
  return _impl_.y_;
}
inline float Vec3::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.y)
  return _internal_y();
}
inline void Vec3::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Vec3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.y)
}

// float z = 3;
inline void Vec3::clear_z() {
  _impl_.z_ = 0;
}
inline float Vec3::_internal_z() const {
  return _impl_.z_;
}
inline float Vec3::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.z)
  return _internal_z();
}
inline void Vec3::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Vec3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
